apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: aneeshrb
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devopsrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: aneesh
